### ISSUE TITLE
Please put 'brightness' icon on the GNOME panel next to (prior to) the 'volume' icon as these functions are in the 'same category'

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [daitj/gnome-display-brightness-ddcutil#78] opened 2022-07-11 10:23 UTC
**Describe the bug**

Currently with the usage of the extension, brightness icon is the last one on the GNOM panel instead of the power icon, what could be the most logical. Illustration bellow.

Please if possible put the icon next to the volume icon _(in theory **the most perfect position would be prior to volume icon** as our screen is more important peripherial that the sound output)_, to be logically consistent.

Lot of thanks for this extension and for all your efforts!

**To Reproduce**

Just use the extension :smile: 

**Journal logs**

Not needed.

**Screenshots**

In vertical case:

![image](https://user-images.githubusercontent.com/25765137/178242457-435bab20-abbb-4317-aeb1-356fd3a6b230.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04
 - GNOME version: 42.2 _(halfly integrated as Ubuntu did)_
 - Extension version: 31

**Additional context**

None

**Comment by daitj** [comment] 2022-07-13 21:58
Duplicate of #75

**Closed by daitj** 2022-07-13 21:58 UTC

**Comment by Tamas-Toth-ebola** [comment] 2022-07-14 18:07
I think it is not a duplication as the other 'bug' report is a simple misunderstanding of an already available function, what I also saw before my report.

But independently the exact state or the interpretation of it I can understand that for both reports would be the most perfect solution is a settings option for it.

Thanks for your time for checking it!
