### ISSUE TITLE
Feature Idea or Document Suggested Workaround: Keyboard Control?

### ISSUE THREAD

**Issue by ryanerwin** [daitj/gnome-display-brightness-ddcutil#22] opened 2021-06-10 04:18 UTC
Curious if you would be interested in adding some kind of keyboard shortcut to control the brightness... Not sure if that's even possible the way that Wayland is relatively restricted for keyboard access, but it was always cool on laptops to be able to control the entire screen brightness via some keyboard shortcuts.

**Comment by daitj** [comment] 2021-06-10 08:44
Duplicate of #21

**Closed by daitj** 2021-06-10 08:44 UTC
